### ISSUE TITLE
Add Sweet caramel to Gnosis Apps

### ISSUE THREAD

**Issue by RedVeil** [popcorndao/sweet-caramel#728]
In order to expose instamint of butter to DAOs we want to add a new App to Gnosis. 
We want to use an iFrame similar to sushiswap to simply display the instamint frontend in Gnosis.

- [x] Sourcify analysis of our contract

- [x] change to eagerconnect that detect when we are embedded in a gnosis page and sets the autoconnect to gnosis instead of anything else

- [x] Our CORS settings and manifest need to be correct so the app can be shown on gnosis.

**Comment by arne-z** [comment]
https://docs.gnosis-safe.io/build-with-safe/sdks/safe-apps/releasing-your-safe-app

https://github.com/popcorndao/sweet-caramel/pull/762

**Comment by arne-z** [comment]
Requirement List for being accepted as a gnosis app:
- manifest.json
- CORS headers
- SSL
- The app auto-connects to the Safe
- Gnosis  review (link to public repo or invitation to private repo)
- Decode Safe App transactions (Sourcify or JSON ABIs)
- After all these are done, create an issue in https://github.com/gnosis/safe-apps-list

**Comment by arne-z** [comment]
On the topic of auto-connecting to the safe the following is said: 
2) The app auto-connects to the Safe
When a user opens the app, it should automatically select the Safe as a wallet. Ensure to check the case if the user previously opened the app outside of the Safe with another wallet.

**Comment by anthonymartin** [comment]
> Decode Safe App transactions (Sourcify or JSON ABIs)
Can you look into what this means @arne-z  or what the level of effort for this might be? 

> The app auto-connects to the Safe
what exactly does this mean? Are we already compliant there since we have the connect button and eager connect?

**Comment by arne-z** [comment]
@anthonymartin To answer your questions:
1. Sourcify is a web service found at https://sourcify.dev (their open-source repo is https://github.com/ethereum/sourcify). It doesn't look like it's a lot of effort, it's just a case of uploading our contract files to sourcify. Specifically, they need Solidity source code and metadata. Sourcify is the preferred way to doing this according to gnosis. However, alternatively, we can provide them with our ABIs as JSON files or with links to verified contracts on Etherscan if we don't want to use sourcify for some reason. I don't see why we wouldn't though.

2. We need to add a check to our eagerconnect that recognizes when the page is running in an iframe on gnosis and when that is the case we need to eagerconnect with the gnosis wallet rather than with whatever wallet the user last used. Probably possible to check this via the URL since gnosis apps run on URLs matching https://gnosis-safe.io/app/share/safe-app?appUrl=XXX&chainId=1

**Comment by arne-z** [comment]
@arne-z Create tickets with action items for moving this forward.

**Comment by arne-z** [comment]
@anthonymartin what should we do with this original ticket now that it is basically superceded by all of the following:
https://app.zenhub.com/workspaces/default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/914
https://app.zenhub.com/workspace/o/popcorndao/sweet-caramel/issues/915
https://app.zenhub.com/workspaces/default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/916
https://app.zenhub.com/workspaces/default-603eb49d1a9a0b0011b49b36/issues/popcorndao/sweet-caramel/917

Should we close this one, or keep it around and have it waiting on all of these?

**Comment by anthonymartin** [comment]
@arne-z - I've converted the ticket to an epic
